HelloBundle\Entity\Post:
    type: entity
    table: hello_post
    repositoryClass: HelloBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        publishedAt:
            type: datetime
    oneToOne:
        seo:
            targetEntity: HelloBundle\Entity\Seo
            cascade: ['persist', 'remove']
    oneToMany:
        comments:
            targetEntity: HelloBundle\Entity\Comment
            mappedBy: post
    manyToOne:
        author:
            targetEntity: HelloBundle\Entity\Author
            inversedBy: posts
    manyToMany:
        tags:
            targetEntity: HelloBundle\Entity\Tag
            inversedBy: posts
            joinTable:
                name: hello_post_tag
                joinColumns:
                    post_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
