<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ProductBundle\Entity\Attribute;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
}
