admin_attribute_group_index:
    path:     /
    defaults: { _controller: "ProductBundle:Admin/AttributeGroup:index" }
    methods:  GET

admin_attribute_group_show:
    path:     /{id}/show
    defaults: { _controller: "ProductBundle:Admin/AttributeGroup:show" }
    methods:  GET

admin_attribute_group_new:
    path:     /new
    defaults: { _controller: "ProductBundle:Admin/AttributeGroup:new" }
    methods:  [GET, POST]

admin_attribute_group_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductBundle:Admin/AttributeGroup:edit" }
    methods:  [GET, POST]

admin_attribute_group_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductBundle:Admin/AttributeGroup:delete" }
    methods:  DELETE
