admin_attribute_index:
    path:     /
    defaults: { _controller: "ProductBundle:Admin/Attribute:index" }
    methods:  GET

admin_attribute_show:
    path:     /{id}/show
    defaults: { _controller: "ProductBundle:Admin/Attribute:show" }
    methods:  GET

admin_attribute_new:
    path:     /new
    defaults: { _controller: "ProductBundle:Admin/Attribute:new" }
    methods:  [GET, POST]

admin_attribute_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductBundle:Admin/Attribute:edit" }
    methods:  [GET, POST]

admin_attribute_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductBundle:Admin/Attribute:delete" }
    methods:  DELETE
